version: '3.8'

services:
  app:
    build: .
    container_name: fullpgportal_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=example
      - DB_NAME=fullpgdb
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: fullpgportal_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: fullpgdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
